# Generated by Django 4.1.4 on 2022-12-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phn_no', models.BigIntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
    ]
