# Generated by Django 4.1.4 on 2022-12-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_med', '0003_carrer_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='job_role',
            field=models.CharField(choices=[('NO', 'Others'), ('TE', 'Technician'), ('DG', 'Designer')], default='NO', max_length=20),
        ),
    ]
