# Generated by Django 4.1.4 on 2023-01-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_med', '0004_alter_carrer_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrer',
            name='job_role',
        ),
        migrations.AddField(
            model_name='carrer',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
